// TurboQuant flash attention template instances
// PROD K × various V types, D=128 only

#include "../fattn-vec-tq.cuh"

// PROD K × TQ MSE V
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO3_0_PROD, GGML_TYPE_TURBO3_0_MSE);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO3_0_PROD, GGML_TYPE_TURBO4_0_MSE);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO4_0_PROD, GGML_TYPE_TURBO3_0_MSE);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO4_0_PROD, GGML_TYPE_TURBO4_0_MSE);

// PROD K × standard V
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO3_0_PROD, GGML_TYPE_Q4_0);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO4_0_PROD, GGML_TYPE_Q4_0);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO3_0_PROD, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO4_0_PROD, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO3_0_PROD, GGML_TYPE_F16);
DECL_FATTN_VEC_TQ_CASE(GGML_TYPE_TURBO4_0_PROD, GGML_TYPE_F16);
